[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['npm run build', 'npx prisma generate']

[start]
cmd = 'npx prisma migrate deploy && npm run start:prod'
